### ISSUE TITLE
I see JWT is mentioned here. How to add jwt into build a OAuth2 server to issue jwt access token and support refresh token?

### ISSUE THREAD

**Issue by stevehu** [strongloop/loopback-component-oauth2#15]

**Comment by raibutera** [comment]
+1

**Comment by richardpringle** [comment]
Hey @stevehu and @raibutera, the best place to ask questions is in one of the following locations: 
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

We're trying to keep the issues section on GitHub for bug reports and feature requests only (just so it's more manageable). 

I see that this issue is over a year old, but if you ask again on one of the channels I mentioned and still don't get any answers, please feel free to re-open this issue and mention me directly in a comment and I will see if we can get you an answer.
